### ISSUE TITLE
Feature Request: Ender Storage upgrade support for MultiStorage mod

### ISSUE THREAD

**Issue by Alphanos** [V0idWa1k3r/SmartBackpacks#1]
Good afternoon,

Thank you for this great mod!  This fills a major gap that has been left in backpack mods.  I expect it should be picked up by a number of modpacks once they realize this.

I did have one feature request.  Currently the Ender Storage Interface Upgrade mentions that it is only usable with [Ender Storage](https://minecraft.curseforge.com/projects/ender-storage-1-8) installed.

Although Ender Storage is the more popular mod, some packs instead use the combination of [MultiStorage](https://minecraft.curseforge.com/projects/multistorage) for ender chests and [EnderTanks](https://minecraft.curseforge.com/projects/endertanks) for fluids due to some additional features they provide.  The concept of the colour-coded ender chests in Ender Storage and MultiStorage is virtually identical, with only a few feature differences like the ability to upgrade the size of a specific ender chest colour code.

Would it be possible to support MultiStorage for the Smart Backpacks Ender Storage upgrade?  I am not certain if this would be difficult to do, since I don't immediately see a source code link on the MultiStorage page.  I am unsure if Ender Storage and MultiStorage share a common original codebase or API.

Thanks again for the great mod!

**Comment by V0idWa1k3r** [comment]
I'll look into MultiStorage integration, seems possible. Since I use reflection instead of direct API calls I don't need a publicly available API to make some things work.
