### ISSUE TITLE
Dupe with backpack magnet

### ISSUE THREAD

**Issue by mrdeadlocked** [V0idWa1k3r/SmartBackpacks#12]
Having the magnet on the backpack causes items to duplicate. 

The best way I've found to duplicate is using the "Place On Block' Feature from Draconic Evolution. If you spam place the item on the wall while right-clicking the wall at the same time you will get multiple of the item. I've tested it by taking the magnet upgrade out and following the same steps no dupe. Put the magnet upgrade back on and it dupe.

![2018-09-15_16-42-57](https://user-images.githubusercontent.com/461352/45590432-a1c84880-b906-11e8-8265-4cf1accde6d1.gif)

**Comment by V0idWa1k3r** [comment]
Are you sure this isn't a client-only "phantom item" and is an actual item that you get on the server? All that the magnet does is calls Entity#onCollideWithPlayer, the same thing minecraft calls when you do physicaly collide with the item. Can you replicate this with anything apart from DE's place-item feature?

**Comment by V0idWa1k3r** [comment]
Hopefully fixed in the next version, at least I am unable to reproduce the issue any more. If it still keeps happening after the next release then it is a mod interaction issue.

**Comment by mrdeadlocked** [comment]
I ran the same test on the newest version and I couldn't reproduce the dupe.
