### ISSUE TITLE
[Suggestion] Advanced Nesting Upgrade

### ISSUE THREAD

**Issue by angelnc1989** [V0idWa1k3r/SmartBackpacks#14]
The Advanced Nesting Upgrade let's you nest backpacks of the same tier.
I need a use for all those Ender Dragon Scales ;-)

**Comment by V0idWa1k3r** [comment]
See [#6](https://github.com/V0idWa1k3r/SmartBackpacks/issues/6). As I've said there it could lead to lag due to upgrades having to iterate with a lot of depth, crashes due to max NBT depth and crashes due to StackOverflow. The last two I can't do anything with.
