### ISSUE TITLE
Feature Request: Support for Draconic Evolution's LootCores (consolidated piles of dropped items)

### ISSUE THREAD

**Issue by Alphanos** [V0idWa1k3r/SmartBackpacks#3]
This is in relation to Smart Backpacks' Pulling Upgrade, which automatically picks things up into the backpack rather than into your regular inventory.

[Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution) includes tools that have the capability to potentially mine hundreds of even thousands of blocks at once.  So to prevent lag, large groups of blocks dropping at once are consolidated into a dropped item called entity.draconicevolution:LootCore rather than having hundreds of separate floating item entities.  This commonly causes cross-mod compatibility issues with mods that are attempting to intercept player item pickup events.  I think Iron Backpacks ran into the same issue for a while at least.

If possible, it would be great if the Pulling upgrade were able to pick up items from a LootCore.  I just tested and [/dank/null](https://minecraft.curseforge.com/projects/dank-null) includes support to pickup LootCore items, in case it would be easier to see an example of code from a similar mod implementing this feature.

Sorry to be opening so many issues on your tracker so quickly for the new mod ;-).  Obviously you have zero obligation to consider any of these feature requests; just proposing them because I think this is a great mod that seems likely to become a new staple mod in a bunch of packs.  Thanks!

**Comment by V0idWa1k3r** [comment]
Don't feel bad, issues and suggestions are always welcome since they allow me to improve the mod. I'll look into DE compatibility however the backpacks might not be able to handle this many items at once anyway but that is the limitation I can't really get around.
This issue also applies to the void upgrade.
