### ISSUE TITLE
Feature Request: Inventory Tweaks Integration

### ISSUE THREAD

**Issue by spocane** [V0idWa1k3r/SmartBackpacks#7]
Would love to have Inventory Tweaks Integration with the backpacks as it is one of my must have mods.

**Comment by V0idWa1k3r** [comment]
Couldn't you already have that by adding a backpack's container to allowed containers in the .xml file as described [here](https://github.com/Inventory-Tweaks/Docs/blob/master/invtweaks_docs/index.txt#L221)?

**Comment by V0idWa1k3r** [comment]
Just a heads-up - inventory tweaks's sort buttons are a bit(5 pixels or so) overlayed on top of the slots. As far as I can tell there isn't much I can do on my side unless InvTweaks impements the necessary hooks in their API. At most I can make it so the buttons don't show up at all but I am not sure about that, I need some feedback on this.

**Comment by spocane** [comment]
Thank You! Seems to be working fine.  The buttons overlapping do not cause any issues for me
